### PR TITLE
Support for additional screen resolutions

### PR DESCRIPTION
**Pull request by antiphon1**
Hello,
I have a few commits that allows for additional screen resolutions, specifically 1024x768.  I have also added support for 120dpi in CSPanel.

### CODE REVIEW

**Comment by onshm** [comment]
thanks. we'll review this asap. a little backed up currently so might take a little bit.

**Comment by solarnz** [comment]
@antiphon1 To make it easier on @Onskreen to accept your pull request, I would suggest removing the Cyanogenmod 9 code that was introduced with 60fc874833a10eb7f3adec737dbd51e2f6a91f95

As it stands this would likely not compile in an AOSP build.

**Comment by antiphon1** [comment]
Sorry about that those CM9 commits should have been put into a different
branch. I went ahead and removed them from the master.

Thanks,
Miller
On Apr 23, 2012 3:37 AM, "Chris Trotman" <
reply@reply.github.com>
wrote:

**Comment by onshm** [comment]
thanks. closing.

**Pull request closed without merging**
